package utilities;

import java.io.IOException;

public class Constants {

	private final String currentDatePath = "./resources/CurrentDate.properties";
	private final String coreLogPath = "./resources/CoreLog/Sample.log";
	private final String testNGXMLPath = "./testNG.xml";
	private final String driverName = "webdriver.chrome.driver";
	private final String driverValue = "resources/chromedriver";
	
	private String templatePath = "./resources/TemplateFile/Template_";
	private String customLogPath = "./resources/CustomLog/Test_";
	private String autoGeneratedScriptPath = "./resources/GeneratedScript/AutomatedScript_";
	private String screenshotPath = "./Screenshots/Screenshot_";

	// SMTP info
	public static String host = "smtp.gmail.com";
	public static String port = "587";
	public static String mailFrom = "mailtogourabbanerjee@gmail.com";
	public static String password = "admin100";
	// message info
	public static String mailTo = "gourab2012@gmail.com";
	public static String subject = "Autogenerated Test Case - Manual steps and Automation script";
	public static String message = "Please Find the test case as manual steps format and Automated Generated Script on that as attachments";
	public static String coreLogValidationFlag = "Linkedin Log - ";

	public String getTemplatePath() throws IOException {
		String templatePATH = templatePath + Utility.readPropertyFile() + ".xls";
		return templatePATH;
	}

	public String getCustomLogPath() throws IOException {
		String customLogPATH = customLogPath + Utility.readPropertyFile() + ".log";
		return customLogPATH;
	}
	
	public String getAutoGeneratedScriptPath() throws IOException {
		String autoGeneratedScriptPATH = autoGeneratedScriptPath + Utility.readPropertyFile() + ".log";
		return autoGeneratedScriptPATH;
	}
	
	public String getScreenshotPath() throws IOException {
		String screenshotPATH = screenshotPath + Utility.readPropertyFile() + ".png";
		return screenshotPATH;
	}

	public String getCurrentDatePath() throws IOException {
		return currentDatePath;
	}

	public String getCoreLogPath() throws IOException {
		return coreLogPath;
	}

	public String getTestNGXMLPath() throws IOException {
		return testNGXMLPath;
	}
	
	public String getDriverName() throws IOException {
		return driverName;
	}
	
	public String getDriverValue() throws IOException {
		return driverValue;
	}
	

}
